**Ahmad Naufal Luthfan Marzuqi - 202210370311072 - DIP B**

1. memahami struktur dataset Electric_Vehicle_Population_Data.csv dengan menampilkan informasi dasar seperti tipe data, statistik deskriptif, dan 5 baris pertama.

In [5]:
import pandas as pd
import numpy as np
from IPython.display import display

df = pd.read_csv('Electric_Vehicle_Population_Data.csv')

print("Informasi Struktur Dataset:")
display(df.info())
print("\nStatistik Deskriptif Dataset:")
display(df.describe(include='all'))
print("\n5 Baris Pertama Dataset:")
display(df.head())

print("\nJumlah Baris dan Kolom:", df.shape)

Informasi Struktur Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235692 entries, 0 to 235691
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         235692 non-null  object
 1   County                                             235689 non-null  object
 2   City                                               235689 non-null  object
 3   State                                              235692 non-null  object
 4   Postal Code                                        235689 non-null  float64
 5   Model Year                                         235692 non-null  int64
 6   Make                                               235692 non-null  object
 7   Model                                              235692 non-null  object
 8   Electric Vehicle Type                              235692 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  235692 non-null  object
 10  Electric Range                                     235656 non-null  float64
 11  Base MSRP                                          235656 non-null  float64
 12  Legislative District                               235198 non-null  float64
 13  DOL Vehicle ID                                     235692 non-null  int64
 14  Vehicle Location                                   235682 non-null  object
 15  Electric Utility                                   235689 non-null  object
 16  2020 Census Tract                                  235689 non-null  float64
dtypes: float64(5), int64(2), object(10)
memory usage: 30.6+ MB

None

Statistik Deskriptif Dataset:

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,235692,235689,235689,235692,235689.000000,235692.000000,235692,235692,235692,235692,235656.000000,235656.000000,235198.000000,2.356920e+05,235682,235689,2.356890e+05
unique,13763,212,788,48,NaN,NaN,46,171,2,3,NaN,NaN,NaN,NaN,957,76,NaN
top,7SAYGDEE6P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,NaN,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,1190,118711,37410,235198,NaN,NaN,101080,49253,186998,139761,NaN,NaN,NaN,NaN,5824,85298,NaN
mean,NaN,NaN,NaN,NaN,98177.656463,2021.406658,NaN,NaN,NaN,NaN,46.262569,787.268328,28.879519,2.353127e+08,NaN,NaN,5.298066e+10
std,NaN,NaN,NaN,NaN,2524.218661,2.991908,NaN,NaN,NaN,NaN,84.045829,7177.668305,14.904644,6.799098e+07,NaN,NaN,1.521066e+09
min,NaN,NaN,NaN,NaN,1731.000000,2000.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,4.385000e+03,NaN,NaN,1.001020e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2020.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,17.000000,2.053457e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98126.000000,2023.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,32.000000,2.522795e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98374.000000,2024.000000,NaN,NaN,NaN,NaN,38.000000,0.000000,42.000000,2.696401e+08,NaN,NaN,5.305307e+10
max,NaN,NaN,NaN,NaN,99577.000000,2025.000000,NaN,NaN,NaN,NaN,337.000000,845000.000000,49.000000,4.792548e+08,NaN,NaN,5.602100e+10

5 Baris Pertama Dataset:

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EBXK,King,Seattle,WA,98178.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,37.0,477309682,POINT (-122.23825 47.49461),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,5YJYGDEE3L,Kitsap,Poulsbo,WA,98370.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,0.0,23.0,109705683,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,KM8KRDAF5P,Kitsap,Olalla,WA,98359.0,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,26.0,230390492,POINT (-122.54729 47.42602),PUGET SOUND ENERGY INC,5.303509e+10
3,5UXTA6C0XM,Kitsap,Seabeck,WA,98380.0,2021,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30.0,0.0,35.0,267929112,POINT (-122.81585 47.64509),PUGET SOUND ENERGY INC,5.303509e+10
4,JTMAB3FV7P,Thurston,Rainier,WA,98576.0,2023,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42.0,0.0,2.0,236505139,POINT (-122.68993 46.88897),PUGET SOUND ENERGY INC,5.306701e+10

Jumlah Baris dan Kolom: (235692, 17)

2. Kode ini mengidentifikasi dan menangani masalah data seperti missing values, outliers (pada Model Year), noise (tahun < 1900), dan duplikat pada dataset kendaraan, lalu menyimpan hasilnya.

In [9]:
print("Jumlah Missing Values per Kolom:")
display(df.isnull().sum())

df['County'] = df['County'].fillna('Unknown')
df['City'] = df['City'].fillna('Unknown')
df['Clean Alternative Fuel Vehicle (CAFV) Eligibility'] = df['Clean Alternative Fuel Vehicle (CAFV) Eligibility'].fillna('Eligibility unknown')

Q1 = df['Model Year'].quantile(0.25)
Q3 = df['Model Year'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Model Year'] < lower_bound) | (df['Model Year'] > upper_bound)]
print("\nJumlah Outliers di Model Year:", len(outliers))
print("Contoh Outliers di Model Year:")
print(outliers[['Model Year']].head())

df = df[(df['Model Year'] >= lower_bound) & (df['Model Year'] <= upper_bound)]

noise = df[df['Model Year'] < 1900]
print("\nJumlah Noise di Model Year (< 1900):", len(noise))
df = df[df['Model Year'] >= 1900]

print("\nJumlah Duplikat:", df.duplicated().sum())
df = df.drop_duplicates()

df.to_csv('Cleaned_Electric_Vehicle_Population_Data.csv', index=False)
print("\nDataset setelah pembersihan disimpan.")

Jumlah Missing Values per Kolom:

VIN (1-10)                                             0
County                                                 0
City                                                   0
State                                                  0
Postal Code                                            3
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                        36
Base MSRP                                             36
Legislative District                                 484
DOL Vehicle ID                                         0
Vehicle Location                                      10
Electric Utility                                       3
2020 Census Tract                                      3
dtype: int64

Jumlah Outliers di Model Year: 0
Contoh Outliers di Model Year:
Empty DataFrame
Columns: [Model Year]
Index: []

Jumlah Noise di Model Year (< 1900): 0

Jumlah Duplikat: 0

Dataset setelah pembersihan disimpan.

3. Kode ini membersihkan inkonsistensi nama di kolom Make dan CompanyName dengan menghapus karakter khusus (termasuk underscore) dan spasi, lalu menstandarisasi ke huruf kapital.

In [20]:
import pandas as pd
import re

df_vehicle = pd.read_csv('Electric_Vehicle_Population_Data.csv')

df_company = pd.read_csv('company_esg_financial_dataset.csv')

print("Nilai Unik di 'Make' (Dataset Kendaraan) Sebelum Pembersihan:")
print(df_vehicle['Make'].unique()[:10])
print("\nNilai Unik di 'CompanyName' (Dataset Perusahaan) Sebelum Pembersihan:")
print(df_company['CompanyName'].unique()[:10])

def clean_name(name):
    if pd.isna(name):  # Tangani nilai NaN
        return name
    cleaned = re.sub(r'[^a-zA-Z0-9]', '', str(name))
    return cleaned.strip().upper()

df_vehicle['Make_Cleaned'] = df_vehicle['Make'].apply(clean_name)
df_company['CompanyName_Cleaned'] = df_company['CompanyName'].apply(clean_name)

print("\nNilai Unik di 'Make_Cleaned' (Dataset Kendaraan) Setelah Pembersihan:")
print(df_vehicle['Make_Cleaned'].unique()[:10])
print("\nNilai Unik di 'CompanyName_Cleaned' (Dataset Perusahaan) Setelah Pembersihan:")
print(df_company['CompanyName_Cleaned'].unique()[:10])

Nilai Unik di 'Make' (Dataset Kendaraan) Sebelum Pembersihan:
['TESLA' 'HYUNDAI' 'BMW' 'TOYOTA' 'NISSAN' 'KIA' 'POLESTAR' 'MAZDA'
 'CHEVROLET' 'VOLVO']

Nilai Unik di 'CompanyName' (Dataset Perusahaan) Sebelum Pembersihan:
['Company_1' 'Company_2' 'Company_3' 'Company_4' 'Company_5' 'Company_6'
 'Company_7' 'Company_8' 'Company_9' 'Company_10']

Nilai Unik di 'Make_Cleaned' (Dataset Kendaraan) Setelah Pembersihan:
['TESLA' 'HYUNDAI' 'BMW' 'TOYOTA' 'NISSAN' 'KIA' 'POLESTAR' 'MAZDA'
 'CHEVROLET' 'VOLVO']

Nilai Unik di 'CompanyName_Cleaned' (Dataset Perusahaan) Setelah Pembersihan:
['COMPANY1' 'COMPANY2' 'COMPANY3' 'COMPANY4' 'COMPANY5' 'COMPANY6'
 'COMPANY7' 'COMPANY8' 'COMPANY9' 'COMPANY10']